openapi: 3.0.3
info:
  description: REST API for a game fair
  title: Game Fair REST API
  contact:
    name: Feira de Jogos do IFSC São José
    email: feiradejogosifscsaojose@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.1.0
externalDocs:
  url: https://github.com/feira-de-jogos/docs
servers:
  - url: https://feira-de-jogos.sj.ifsc.edu.br/api/v2
tags:
  - name: user
    description: User related operations
  - name: machine
    description: Machine related operations
paths:
  /login:
    post:
      description: User authentication
      tags:
        - user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
        "302":
          description: Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
      security:
        - user_auth:
            - read:user
  /operation:
    post:
      description: Bank operation
      tags:
        - user
      requestBody:
        description: Bank information
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/operation-request"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/operation-response"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "429":
          description: Too Many Requests
      security:
        - user_auth:
            - write:user
            - read:user
  /statement:
    get:
      description: Bank statement
      tags:
        - user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/statement-response"
        "401":
          description: Unauthorized
      security:
        - user_auth:
            - read:user
components:
  schemas:
    login-response:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
          description: user id
    operation-request:
      type: object
      properties:
        type:
          type: string
          description: debit, credit or transfer
          example: credit
        to:
          type: integer
          format: int32
          description: destination or product id
          example: 1
        value:
          type: integer
          format: int32
          description: value to be transferred
          example: 100
    operation-response:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: operation id
          example: 1000
    statement-response:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: operation id
          example: 1000
        type:
          type: string
          description: debit, credit or transfer
          example: credito
        product:
          type: string
          description: product name
          example: água mineral
        value:
          type: integer
          format: int32
          description: value to be transferred
          example: 100
        timestamp:
          type: string
          description: operation date and time
          format: date-time
          example: 2024-10-01T00:00:00Z
  securitySchemes:
    user_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://hippogames.dev/api/oauth/redirect
          scopes:
            write:user: bank operations
            read:user: user information
