openapi: 3.0.3
info:
  contact:
    name: Feira de Jogos do IFSC São José
    email: feiradejogosifscsaojose@gmail.com
  description: REST API for a game fair
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Game Fair REST API
  version: 0.1.0
externalDocs:
  url: https://github.com/feira-de-jogos/docs
servers:
  - url: https://feira-de-jogos.sj.ifsc.edu.br/api/v2
tags:
  - description: User related operations
    name: user
  - description: Machine related operations
    name: machine
paths:
  /login:
    post:
      description: User authentication
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
          description: OK
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
          description: Created
        "302":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login-response"
          description: Found
      security:
        - user_auth:
            - read:user
  /operation:
    post:
      description: Bank operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/operation-request"
        description: Bank information
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/operation-response"
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "402":
          description: Payment Required
        "403":
          description: Forbidden
        "429":
          description: Too Many Requests
      security:
        - user_auth:
            - write:user
            - read:user
  /statement:
    get:
      description: Bank statement
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/statement-response"
                type: array
          description: OK
        "401":
          description: Unauthorized
      security:
        - user_auth:
            - read:user
components:
  schemas:
    login-response:
      properties:
        id:
          description: user id
          example: 1
          format: int32
          type: integer
    operation-request:
      properties:
        type:
          description: debit, credit or transfer
          example: credit
          type: string
        to:
          description: destination or product id
          example: 1
          format: int32
          type: integer
        value:
          description: value to be transferred
          example: 100
          format: int32
          type: integer
    operation-response:
      properties:
        id:
          description: operation id
          example: 1000
          format: int32
          type: integer
    statement-response:
      properties:
        id:
          description: operation id
          example: 1000
          format: int32
          type: integer
        product:
          description: product name
          example: água mineral
          type: string
        timestamp:
          description: operation date and time
          example: 2024-10-01T00:00:00Z
          format: date-time
          type: string
        type:
          description: debit, credit or transfer
          example: credito
          type: string
        value:
          description: value to be transferred
          example: 100
          format: int32
          type: integer
  securitySchemes:
    user_auth:
      flows:
        implicit:
          authorizationUrl: https://hippogames.dev/api/oauth/redirect
          scopes:
            read:user: user information
            write:user: bank operations
      type: oauth2
